name: Build & Publish Docker Image

on:
  push:
    branches: [ main, fix-button ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      if: ${{ !env.ACT }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Build Docker image
      run: docker build . --tag ${{ secrets.DOCKERHUB_USER }}/dbio-client:$GITHUB_SHA --tag ${{ secrets.DOCKERHUB_USER }}/dbio-client:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Push Docker image
      run: docker push --all-tags ${{ secrets.DOCKERHUB_USER }}/dbio-client

